spring.application.name=TelegramBots

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.fr.ses10doigts.telegrambots=DEBUG

telegram.enabled=true
telegram.bot-token=YourBotToken
telegram.polling-enabled=true

telegram.allowed-user-ids[0]=YourLongId
telegram.auto-register-commands=true
telegram.configure-menu-button=true

telegram.retry.enabled=true
telegram.retry.max-attempts=3
telegram.retry.delay-seconds=2